GET https://jsonplaceholder.typicode.com/posts HTTP/1.1

###

POST https://jsonplaceholder.typicode.com/posts HTTP/1.1
content-type: application/json

{
    "userId": 1,
    "id": 7,
    "title": "xablau",
    "body": "A verdade é uma grande mentira."
}
